import { Injectable, NotFoundException, BadRequestException, ForbiddenException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { UserRole } from '@prisma/client';

@Injectable()
export class InvoicesService {
  constructor(private prisma: PrismaService) {}

  async create(data: any, user: any) {
    // We disable manual invoice creation here because invoices are now securely 
    // auto-generated by the SalesService during a POS checkout.
    throw new BadRequestException('Invoices must be created via the New Sale POS interface.');
  }

  async findAll(query: any) {
    const { branchId, status, search, user } = query;
    const where: any = {};

    // Scope restrictions based on role
    if (user?.role === UserRole.BRANCH_MANAGER) {
      where.branchId = user.branchId;
    } else if (branchId) {
      where.branchId = branchId;
    }

    if (status) where.status = status;
    if (search) {
      where.OR = [
        { invoiceCode: { contains: search, mode: 'insensitive' } },
        { customer: { name: { contains: search, mode: 'insensitive' } } }
      ];
    }

    return this.prisma.invoice.findMany({
      where,
      include: {
        customer: true,
        branch: { select: { id: true, name: true } },
        sale: { include: { saleItems: { include: { product: true } } } }
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  async findOne(id: string, user?: any) {
    const invoice = await this.prisma.invoice.findUnique({
      where: { id },
      include: {
        customer: true,
        branch: true,
        sale: { include: { saleItems: { include: { product: true } } } }
      }
    });

    if (!invoice) throw new NotFoundException('Invoice not found');

    if (user?.role === UserRole.BRANCH_MANAGER && invoice.branchId !== user.branchId) {
      throw new ForbiddenException('You can only view invoices for your assigned branch');
    }

    return invoice;
  }

  async getDashboardStats(user?: any) {
    const where: any = {};
    
    if (user?.role === UserRole.BRANCH_MANAGER) {
      where.branchId = user.branchId;
    }

    const invoices = await this.prisma.invoice.findMany({ where });

    const totalOutstanding = invoices.reduce((sum, inv) => sum + Number(inv.balance || 0), 0);
    const totalPaid = invoices.reduce((sum, inv) => sum + Number(inv.amountPaid || 0), 0);
    const overdueCount = invoices.filter(inv => inv.dueDate && new Date(inv.dueDate) < new Date() && Number(inv.balance) > 0).length;

    return {
      totalInvoices: invoices.length,
      totalOutstanding,
      totalPaid,
      overdueCount
    };
  }

  async recordPayment(id: string, amount: number, performedById: string) {
    if (amount <= 0) throw new BadRequestException('Payment amount must be greater than zero');

    const invoice = await this.prisma.invoice.findUnique({ where: { id } });
    if (!invoice) throw new NotFoundException('Invoice not found');

    if (Number(invoice.balance) < amount) {
      throw new BadRequestException(`Payment amount (${amount}) exceeds the remaining balance (${invoice.balance})`);
    }

    const newAmountPaid = Number(invoice.amountPaid || 0) + amount;
    const newBalance = Number(invoice.total) - newAmountPaid;
    
    // Automatically flag as PAID if balance hits 0
    const newStatus = newBalance <= 0 ? 'PAID' : 'PENDING';

    const updatedInvoice = await this.prisma.invoice.update({
      where: { id },
      data: {
        amountPaid: newAmountPaid,
        balance: newBalance,
        status: newStatus,
      },
      include: { customer: true, branch: true }
    });

    // Log the payment activity so everyone can see it in the dashboard feeds
    await this.prisma.activityFeed.create({
      data: {
        type: 'PAYMENT_RECEIVED',
        branchId: updatedInvoice.branchId,
        title: 'Invoice Payment Received',
        message: `Payment of KES ${amount.toFixed(2)} received for Invoice ${updatedInvoice.invoiceCode}`,
        entityId: updatedInvoice.id,
        entityType: 'Invoice',
        visibleToBranch: true,
      }
    });

    return updatedInvoice;
  }
}
